version: '3'
services:
    store:
        build: ./Store   
        depends_on: 
            - mysql
            - mongodb
        ports: 
            - "4000:8080"
        networks:
            - web
        restart: always
        links:
            - mysql
            - mongodb
        restart: always

    cart:
        build: ./Cart
        ports: 
            - "4001:8080"
        networks: 
            - web
        restart: always

    # nginx:
    #     image: nginx
    #     ports:
    #         - "8080:8080"
    #     volumes:
    #         - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #     networks:
    #         - web
    #     restart: always
  

    mongodb:
        image : mongo:latest
        container_name: mongodb
        volumes:
            - mongodb_data_container:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
    
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'everything'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3308:3306'
        expose:
            - '3306'
        volumes:
            - mysql_data_container:/var/lib/mysql

volumes:
    mongodb_data_container:
    mysql_data_container:

networks:
  web:
    driver: bridge
