version: '3'
services:
    store:
        build: ./Store   
        restart: always
        depends_on: 
            - mysql_server
            - mongodb
        environment: 
            - MYSQL_HOST=mysql_server
            - MYSQL_PASSWORD=password
            - MYSQL_USER=root
            - MYSQL_DATABASE=everything
            - MYSQL_PORT=3306
            - MONGODB_URI=mongodb://mongodb:27017

    product:
        build: ./Product   
        depends_on: 
            - mongodb
        restart: always
        environment: 
            - MONGODB_URI=mongodb://mongodb:27017
        restart: always

    cart:
        build: ./Cart
        restart: always

    nginx:
        image: nginx
        ports:
            - "8080:8080"
        volumes:
            - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./Nginx/certs:/etc/nginx/certs:ro
        restart: always
  
    mongodb:
        image : mongo:latest
        container_name: mongodb
        volumes:
            - mongodb_data_container:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
    
    mysql_server:
        image: mysql:8.0
        environment: 
            - MYSQL_DATABASE=everything
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        restart: always
        # volumes:
        #     - mysql_data_container:/var/lib/mysql

volumes:
    mongodb_data_container:
    mysql_data_container:

# networks:
#   web:
#     driver: bridge
